baseurl = "http://fibery.ru/"
languageCode = "ru-ru"
title = "Fibery - магазин ниток"
theme = "hugo-identity-theme"
publishdir = "public"
canonifyurls = true

[params]
	name = "Fibery"
	position = "магазин ниток"
    avatar = "klubok.png"
    background = "bg4.jpg"
    email = "order@fibery.ru"

    [[params.social]]
        title = "Email"
        icon = "fa-envelope-o"
        link = "mailto:order@fibery.ru"

	[[params.social]]
		title = "Instagram"
		icon = "fa-instagram"
		link = "https://www.instagram.com/fibery.ru/"

	[[params.social]]
		title = "Facebook"
		icon = "fa-facebook"
		link = "https://www.facebook.com/fibery.ru"

	# Footer settings
	[params.footer]
		copyright = "команда Fibery"
