baseurl = "http://fibery.ru/"
languageCode = "ru-ru"
title = "Fibery - магазин ниток"
theme = "hugo-identity-theme"
publishdir = "public"
canonifyurls = true

[params]
	name = "Fibery"
	position = "магазин ниток"
    avatar = "klubok.png"

	[[params.social]]
		title = "Twitter"
		icon = "fa-twitter"
		link = "#"

	[[params.social]]
		title = "Instagram"
		icon = "fa-instagram"
		link = "#"

	[[params.social]]
		title = "Facebook"
		icon = "fa-facebook"
		link = "#"

	# Footer settings
	[params.footer]
		copyright = "команда Fibery"
